### PR TITLE
added openers for windows, config and data files.

### PR DESCRIPTION
**Pull request by Tieske**
Also added a __call metamethod on the main module table as a shortcut.

### CODE REVIEW

**Comment by hishamhm** [comment]
Not sure I like the __call shortcut. It wasn't obvious for me if did `datafile.open` or `datafile.path`.

As for the openers, cool! I think we can even merge them into a single windows.lua opener. This makes me think that the unix_config.lua could be extended to look into other classic Unix paths and turn into unix.lua as well.

**Comment by hishamhm** [comment]
I'll merge and then perform the changes here!

**Comment by Tieske** [comment]
If 9 out of 10 times I'd use `myfile = datafile.open(filename)` then I find it a bit clumsy, and I would prefer the shortcut. But that is a matter of opinion of course.

**Comment by hishamhm** [comment]
The idea is still rough on the edges, but what I have in mind is introducing something like a `namespace` method to avoid all the `myapp/foo` paths (since not all paths are best encoded as x/y/myapp/foo, in some places they may be x/myapp/y/foo)

```lua
local files = datafile:namespace("myapp")
files:open("foo.cfg")
files:open("bar.cfg")
```
or
```lua
local config = datafile:namespace("myapp", "config")
config:open("foo.cfg")
config:open("bar.cfg")
```

**Comment by Tieske** [comment]
hmmmm... Don't overdo this. It finds files based on LuaRocks, platform standards and a few hunches. Getting this "right" is pretty much impossible I think.
The current code finds files. How a bout finding the location for writing a file? platforms have different abstraction on what a config file or a datafile comprises. Diffferent ideas, about what single user, multi-user/public, or system files are. There is no one-size-fits-all here.

I'd just drop the traversal and leave it there. My 2cts.

**Comment by hishamhm** [comment]
Yeah, I guess you're right. Thanks for the reality check.

I realize that finding a location to write new files is near impossible, unless the installation creates a directory and the program looks for that instead.

I started to think about the namespaces thing when I realized that rockspecs install data files using things such as "conf/" that end up in _tree_/lib/luarocks/rocks/_rockname_/_version_/conf, so running `datafile.path("rockname/conf")` doesn't find these files. (The case in point was trying to use datafile to clean up the code in the patch section of [this rockspec](https://rocks.moonscript.org/manifests/daurnimator/prosody-scm.trunk.nightly547-0.rockspec)).

**Comment by hishamhm** [comment]
Ok, so I merged win_config and win_data (fixing stuff in datafile.util to make them simpler). Please give it a spin! If changes look good, I'll release datafile 0.2.

**Pull request merged**
