### PR TITLE
add bin-script known issue to readme

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by Tieske** [comment]
Since coverage decreased by updating the readme (?), I had a look at the test configuration and updated that as well, to include only the actual `datafile` code and nothing else.

**Comment by hishamhm** [comment]
Oh, this is a nasty limitation. I'm not even sure I was aware of it. I'd rather try to think a way to fix it rather than just documenting it.

I'll give this some thought. At first glance it doesn't sound like something fully fixable in pure Lua, but we might do some heuristics like using `arg[0]` and maybe OS-specific environment variables.

**Comment by Tieske** [comment]
You cannot fix. Because multiple rocks might write the same script in the `bin` directory (overwriting each other, which is another problem, but that is what it is because it is in the system path). And because of that, it cannot be fixed.

By the way: the description is a bit elaborate. A shorter version would be to move the commandline script in a module. And add a bootstrap-script in `bin` that loads and executes the module.

**Comment by hishamhm** [comment]
@Tieske if we're dealing with a LuaRocks-installed bin script, the luarocks-aware datafile loader should be able to cheat and ask the LuaRocks loader about it.

I'll try hacking something together.

**Comment by Tieske** [comment]
ping @hishamhm

**Comment by hishamhm** [comment]
@Tieske I could not reproduce this. When I run `cd test; luarocks install test-datafile-scm-1.rocksec` and then I run the installed `test_script`, it works.

BTW, I just pushed release 0.6 with a fix for LR3.

**Comment by hishamhm** [comment]
I'm closing this for now -- if the problem persists, let's reopen and discuss.

**Comment by Tieske** [comment]
@hishamhm can you merge the `.luacov` config file anyway?

**Pull request closed without merging**
